apiVersion: v1
kind: Secret
metadata:
  name: db-user
data:
  username: dGVzdHVzZXI=  #this is the base64 encoded value of testuser
  password: dGVzdEAxMjM=  #this is the base64 encoded value of test@123